### ISSUE TITLE
Testovi

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim3#26]
Da li vama prolaze hibernate testovi?
Jeste li ažurirali skriptu za bazu podataka?

**Comment by mirhat** [comment]
Ne može da pronađe bazu Tim3. Pokušao sam da stavim create u konfiguraciju al opet ne radi?

**Comment by deancupovic** [comment]
Greškom je bila kreirana baza tim3 umjesto Tim3. Sada je u redu.
