### ISSUE TITLE
 Javlja izuzetak u MessageBox-u

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#27]
Komponenta:
PrijavaForma

commit ID:
a42675f9e8ea7254bccc6f495997c5c07977fba2

Opis problema:
Kod unosa pogrešnih login podataka javlja izuzetak u MessageBox-u

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Unijeti pogrešne podatke za login
3. Kliknuti na dugme "Prijava"

Dobijeni rezultat:
- Pored MessageBox-a koji obavještava o neuspjeloj prijavi, naknadno se pojavi i MessageBox koji 
  prikazuje naziv izuzetka koji se desio (
  ![1 1 1](https://cloud.githubusercontent.com/assets/7081540/7820367/59e0be20-03e8-11e5-8e03-4368267bfccc.PNG)
  )

Očekivani rezultat:
- Obavještenje o pogrešnim login podacima i spriječavanje rada na aplikaciji

**Comment by Ilvana** [comment]
Uklonjen viška JOptionPane :D
