### ISSUE TITLE
Nema validacije kod kreiranja izvještaja

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#28]
Komponenta:
IzvjestajiForma

commit ID:
b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Dozvoljava kreiranje izvještaja za budućnost te da je početni datum hronološki poslije krajnjeg datuma

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Izvještaji"
4. Na tabu "Prodane karte" unijeti početni datum 07/05/2020 a u polje krajnji datum unijeti 12/05/2017
5. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
- Izvještaj uspješno kreiran (http://prntscr.com/79p6tn)

Očekivani rezultat:
- Prijava o gore navedenim greškama

**Comment by Ilvana** [comment]
Riješeno, dodan if uslov za provjeru datuma u odnosu na danasnji kao i provjera da li je pocetni prije krajnjeg
