### ISSUE TITLE
Validacija nije intuitivn

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#29]
Komponenta:
IzvjestajiForma

commit ID:
 b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Validacija nije intuitivna. Program spriječi kreiranje izvještaja bez navođenja razloga. Ponovo se prikazuje i MessageBox sa izuzetkom.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Izvještaji"
4. Na tabu "Autobuske linije" unijeti početni datum 21/05/2015, krajnji datum 14/05/2015, početno vrijeme 1.1h i 1.1 m te krajnje vrijeme 0.6 h i 0.5 m
5. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
- Obavijest da izvještaj nije kreiran bez navođenja razloga za to (http://prntscr.com/79pfgk) i MessageBox o bačenom izuzetku (http://prntscr.com/79pg37)

Očekivani rezultat:
- Validacija tokom samog popunjavanja forme ili da se po kliku na dugme za generisanje izvještaja 
  izvrši i obavještavanje o tačnim greškama na formi

**Comment by Ilvana** [comment]
Dodana provjera uslova :D
