### ISSUE TITLE
Nema validacije za sate i datume

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#30]
Komponenta:
IzvjestajiForma

commit ID:
b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Uspješno kreiranje izvještaja kod kojeg su sati negativne vrijednosti, početno vrijeme hronološki prije krajnjeg

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Izvještaji"
4. Na tabu "Autobuske linije" unijeti početni datum 29/05/2015, krajnji datum 19/05/2015, početno vrijeme -2h i 2 m te krajnje vrijeme -2 h i 2 m
5. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
- Uspješno kreiran izvještaj (http://prntscr.com/79plmk)

Očekivani rezultat:
- Spriječeno kreiranje izvještaja uz prikladnu obavijest o razlogu

**Comment by Ilvana** [comment]
Rijeseno :D
