### ISSUE TITLE
Kod validacije ispisuje i izuzetke

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#31]
Komponenta:
IzvjestajiForma

commit ID:
b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Kod validacije ispisuje i izuzetke

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Izvještaji"
4. Na tabu "Vozači" unijeti random vrijednost JMBG-a vozača
5. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
-Obavijest o neuspjelom kreiranju izvještaja pa zatim obavijest o razlogu zašto izvještaj nije kreiran uz navođenje naziva izuzetka koji je bačen (http://prntscr.com/79puqb)

Očekivani rezultat:
- Samo obavijest o razlogu zbog koje izvještaj nije kreiran a koja će biti jasna svakom profilu korisnika

**Comment by Ilvana** [comment]
Pa u obavijesti kaze da se moraju cifre unijeti i to je validacija polja, valjda ce korisnik shvatiti, ne znamo bolji nacin da se to kaze :D
