### ISSUE TITLE
Nije omogućeno korištenje afrikata

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#32]
Komponenta:
IzvjestajiForma, RadniciForma, KorisniciForma

commit ID:
b0124ced40093fa29e4443ce8bb8122361b49486
ac726ce67f27c618ce84bea2386e184c7b6552e4
aaced62f94794d6fcde25742ed34b5f1ff25732a

Opis problema:
Nije omogućeno korištenje afrikata

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Izvještaji"
4. Na tabu "Vozači" unijeti vrijednost JMBG-a 0303992110034
5. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
-Izvještaj kreiran ali je afrikat u prezimenu zamijenjen sa ?. Takvo stanje je i samoj bazi.
(Ćazim Ćatić --> ?azim ?ati?) http://prntscr.com/79q1ne   http://prntscr.com/79q22j

Očekivani rezultat:
- Čuvanje ispravnog imena/prezimena.

**Comment by mirhat** [comment]
Ispravljeno
Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/f628740c1511936dbeae5e59596077083163ba6e
