### ISSUE TITLE
Nepraktično izvještavanje o greškama

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#33]
Komponenta:
KorisniciForma
AutobusiForma
RadniciForma
AutobuskeLinijeForma

commit ID:
aaced62f94794d6fcde25742ed34b5f1ff25732a 
f833da11e601700f5963401d13297e4407632cac
ac726ce67f27c618ce84bea2386e184c7b6552e4
bfbb564d295332745d24fb19840a1931014de5a6 

Opis problema:
Nepraktično izvještavanje o greškama

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Evidencija radnika" /"Evidencija autobuskih linija" / "Evidencija autobusa"/ "Korisnički računi"
4. Ostaviti nepopunjenu formu
5. Kliknuti na "Dodaj"

Dobijeni rezultat:
-Obavijest o grešci kod koje je navedena greška za svako od polja pojedinačno 

Očekivani rezultat:
- Obavijest da sve polja moraju biti popunjena

**Comment by Ilvana** [comment]
Riješeno je da iskoci samo jedan prozor, to se slazemo, a i dalje smotramo da treba korisnik da se obavijesti sta treba unijeti odmah, da zna, svakako je ovaj bug nekako subjetivan, ako se svidja nama, ne mora se ostalim svidjat, valjda je bitno da se greske ispisu koje su, a na koji nacin, to je na nama da odlucimo :D
