### ISSUE TITLE
Identifikacija radnika samo po imenu

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#34]
Komponenta:
AutobuskeLinijeForma

commit ID:
bfbb564

Opis problema:
U comboBox-u se ispisuje samo ime radnika bez ikakvog drugog načina da se identificira koji je radnik u pitanju

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Evidencija autobuskih linija"
4. Pokušati odabrati vozača za kreiranje autobuske linije

Dobijeni rezultat:
-Lista imena vozača

Očekivani rezultat:
Lista vozača prema kojoj se može jedinstveno utvditi o kojem je vozaču riječ (http://prntscr.com/79qign)

**Comment by sumejabotulja** [comment]
Pored imena vozača dodan je i njegov jmbg tako da se može jedinstveno utvrditi o kojem vozaču je riječ.
