### ISSUE TITLE
Nepoznat razlog zbog kojeg se ne može kreirati autobuska linija

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#35]
Komponenta:
AutobuskeLinijeForma

commit ID:
bfbb564

Opis problema:
Nepoznat razlog zbog kojeg se ne može kreirati autobuska linija

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer (username: neko; password:neko)
3. Kliknuti na dugme "Evidencija autobuskih linija"
4. Popuniti podatke prema datoj slici
5. Kliknuti na dugme "Dodaj"

Dobijeni rezultat:
Neuspjelo kreiranje autobuske linije (http://prntscr.com/79qlq6)

Očekivani rezultat:
Uspješno kreiranje linije ili bar obavještenje o razlogu neuspjeha

**Comment by sumejabotulja** [comment]
Linija se nije mogla dodati zbog nepravilnog formata vremena, međutim uspješno je riješen taj problem postavljanjem formatted textboxa za unos vremena i dodavanjem validacije za sate i minute.
