### ISSUE TITLE
Problem sa resize frejma

### ISSUE THREAD

**Issue by ArnelaBesic** [SoftverInzenjeringETFSA/SI2014Tim3#36]
Komponenta:
AutobuskeLinijeForma kao primjer
svaki jframe projekta

commit ID:
bfbb564

Opis problema:
Otvorenom prozoru se može mijenjati veličina ali se njegov sadržaj ne prilagođava toj promjeni

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju u bilo kom režimu
2. Promijeniti veličinu otvorenog prozora

Dobijeni rezultat:
Smanjena veličina prozora, sakriven sadržaj prozora (http://prntscr.com/79rb73)

Očekivani rezultat:
Pravilno smanjenje/povećanje veličine prozora

**Comment by sumejabotulja** [comment]
Onemogućeno mijenjanje veličine prozora  postavljanjem opcije "resizable" na "false".
