### ISSUE TITLE
Izuzetak pri izmjeni radnika sa JMB koji je u obrisan u istoj sesiji

### ISSUE THREAD

**Issue by EldarGranulo** [SoftverInzenjeringETFSA/SI2014Tim3#49]
Komponenta:
RadniciForma

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Pojava izuzetka nakon pokušaja izmjene podataka nad radnikom sa JMBG koji je neposredno prije toga obrisan

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se sa podacima username:neko, password:neko
3. Kliknuti na dugme "Evidencija radnika"
4. Zatim kliknuti na "Modifikuj"
5. U polje za JMBG unijeti JMBG koji postoji u bazi podataka
6. Kliknuti na "Pronađi"
7. Otići na tab "Izbriši"
8. Unijeti isti JMBG, kliknuti na "Izbriši"
9. Vratiti se na prethodnu formu i kliknuti "Pronađi"

Dobijeni rezultat:
http://prntscr.com/79swdk

Očekivani rezultat: Ispis greške

**Comment by Ilvana** [comment]
Riješeno, sada ispise da nije moguce modifikovati tog radnika.
