### ISSUE TITLE
Izuzetak pri generisanju izvještaja za vozača koji ima isto ime kao neki drugi radnik

### ISSUE THREAD

**Issue by EldarGranulo** [SoftverInzenjeringETFSA/SI2014Tim3#50]
Komponenta:
IzvjestajiiForma

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Pojava izuzetka nakon pokušaja generisanja izvještaja za vozača

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se sa podacima username:neko, password:neko
3. Kliknuti na dugme Evidencija radnika
4. Dodati radnika sa imenom Eldar, prezimenom Eldar i JMBG 1234567891011, uloga menadžer
5. Dodati radnika sa imenom Eldar, prezimenom Eldar i JMBG 1234567891012, uloga vozač
6. Kliknuti na dugme "Nazad"
7. Kliknuti na dugme "Izvještaji"
8. Zatim kliknuti na tab "Vozači"
9. U polje za JMBG unijeti JMBG 1234567891011
6. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
http://prntscr.com/79t49f
Stanje u bazi:
http://prntscr.com/79t4ni

Očekivani rezultat: Generisan izvještaj za vozača

**Comment by mirhat** [comment]
Ispravljeno.
Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/f9f8f730074407b8475bba28bf93a0f85c7ba1ea
