### ISSUE TITLE
Mogućnost kreiranja izvještaja za vozača za radnika koji nema ulogu vozač

### ISSUE THREAD

**Issue by EldarGranulo** [SoftverInzenjeringETFSA/SI2014Tim3#51]
Komponenta:
IzvjestajiiForma

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Pojava izuzetka nakon pokušaja generisanja izvještaja za vozača

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se sa podacima username:neko, password:neko
3. Kliknuti na dugme "Izvještaji"
4. Zatim kliknuti na tab "Vozači"
5. U polje za JMBG unijeti JMBG radnika koji nema ulogu vozač
6. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
Kreira se prazan izvještaj za radnika, iako radnik nema ulogu vozača.

Očekivani rezultat: Generisan izvještaj za vozača

**Comment by Ilvana** [comment]
Dodano uslov i ispitivanje, da li je radnik vozac ili ne
