### ISSUE TITLE
Izuzetak pri izmjeni autobuske linije nakon dodavanja više autobuskih linija sa istim brojem

### ISSUE THREAD

**Issue by EldarGranulo** [SoftverInzenjeringETFSA/SI2014Tim3#52]
Komponenta:
AutobuskeLinijeForma

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Pojava izuzetka nakon pokušaja izmjene podataka za autobusku liniju sa brojem za koji je prethodno dodano više linija kroz funkciju dodavanja

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se sa podacima username:neko, password:neko
3. Kliknuti na dugme "Evidencija autobuskih linija"
4. Kliknuti na tab "Dodaj"
5. Popuniti formu ispravnim podacima i izabrati broj linije 1
6. Kliknuti na dugme "Dodaj"
7. Ponoviti ovaj postupak, ponovo izabrati broj linije 1
8. Ponoviti 6.
9. Otići na tab modifikuj
10. Izabrati liniju 1 i kliknuti "Pronađi"

Dobijeni rezultat:
http://pokit.org/get/?94dd26860af3b9c241e7fa5948093ff6.jpg

Očekivani rezultat: Popunjena forma za izmjenu podataka

**Comment by Ilvana** [comment]
U bazu je rucno uneseno vise linija sa istim brojem linije, to je kroz forme nemoguce iz tog razloga se javio izuzetak.
