### ISSUE TITLE
Izuzetak pri brisanju autobuske linije nakon dodavanja više autobuskih linija sa istim brojem

### ISSUE THREAD

**Issue by EldarGranulo** [SoftverInzenjeringETFSA/SI2014Tim3#53]
Komponenta:
AutobuskeLinijeForma

commit ID:
b0124ce

Opis problema:
Pojava izuzetka nakon pokušaja izmjene podataka za autobusku liniju sa brojem za koji je prethodno dodano više linija kroz funkciju dodavanja

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se sa podacima username:neko, password:neko
3. Kliknuti na dugme "Evidencija autobuskih linija"
4. Kliknuti na tab "Dodaj"
5. Popuniti formu ispravnim podacima i izabrati broj linije 1
6. Kliknuti na dugme "Dodaj"
7. Ponoviti ovaj postupak, ponovo izabrati broj linije 1
8. Ponoviti 6.
9. Otići na tab "Izbriši"
10. Izabrati liniju 1 i kliknuti "Pronađi"

Dobijeni rezultat:
http://pokit.org/get/?94dd26860af3b9c241e7fa5948093ff6.jpg

Očekivani rezultat: Popunjena forma sa podacima o liniji koju treba obrisati

**Comment by Ilvana** [comment]
Rucno uneseno vise linija sa istim brojem linije, sto je kroz forme nemoguce ;D
