### ISSUE TITLE
Mogućnost kreiranja izvještaja za nevalidne vrijednosti početnog i krajnjeg vremena

### ISSUE THREAD

**Issue by EldarGranulo** [SoftverInzenjeringETFSA/SI2014Tim3#54]
Komponenta:
izvjestajiForma

commit ID:
b0124ce

Opis problema:
Izvještaj se generiše iako su unesene besmislene vrijednosti početnog i krajnjeg vremena u satima i minutama

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se sa podacima username:neko, password:neko
3. Kliknuti na dugme "Izvještaji"
4. Kliknuti na tab "Autobuske linije"
5. Za početni datum izabrati 8.05.2015, a krajnji 22.05.2015.
6. Za početno vrijeme unijeti 25 h i 12 m, a krajnje 26 h i 15 m
7. Kliknuti na generiši izvještaj

Dobijeni rezultat:
http://pokit.org/get/?a3f51d99fbf2e17b9263cd53310d0e6c.jpg

Očekivani rezultat: Poruka o nevalidnosti unesenih sati i minuta koji bi trebali biti u opsegu od 0 - 24 za sate i 0 - 59 za minute

**Comment by Ilvana** [comment]
Rijeseno, dodata provjera
