### ISSUE TITLE
Mogućnost unošenja nevalidnog vremena

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#55]
Komponenta:
Obrazac "Autobuske linije"

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/b0124ced40093fa29e4443ce8bb8122361b49486

Opis greške:
Sistem dozvoljava unos nevalidnog vremena tj. vremena koje izlazi iz opsega dozvoljenih vrijednosti 0-24 za sate i 0-59 za minute.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Odabrati dugme "Evidencija autobuskih linija"
4. Unijeti validne podatke na polja obrasca uključujući i nevalidno vrijeme, npr 30:00

Očekivani rezultat: Obavijest da je vrijeme nevalidno i sprječavanje dodavanja autobuske linije.

Dobijeni rezultat: Obavijest da je autobuska linija uspješno kreirana:

http://prntscr.com/7aq6tu

**Comment by sumejabotulja** [comment]
Ispravljeno u commitu a2f8bc9785c7fe3ffb230b8966de42877611ba4c.
