### ISSUE TITLE
Kapacitet autobusa

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#56]
Komponenta:
Obrazac "Evidencija autobusa"

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/b0124ced40093fa29e4443ce8bb8122361b49486

Opis greške:
Sistem dozvoljava unos 60 za kapacitet, a prilikom unošenja broja većeg od 60 ispisuje grešku koja kaže da kapacitet mora biti manji od 60.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Odabrati dugme "Evidencija autobusa"
4. Popuniti sva polja obrasca sa validnim vrijednostima, a u polje kapacitet unijeti broj 60

Dobijeni rezultat je ispravno dodavanje autobusa:
http://prntscr.com/7aq9zq

Očekivani rezultat: Nemogućnost dodavanja ili ispravka poruke na mesage boxu koja se ispiše kada se za kapacitet unese broj veći od 60:
http://prntscr.com/7aqail

**Comment by Ilvana** [comment]
Popravljena poruka o greški
