### ISSUE TITLE
Prikaz izbrisanog autobusa u listi postojećih autobusa

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#57]
Komponenta:
Obrazac "Evidencija autobusa"

commit ID:
b0124ce

Opis greške:
Nakon brisanja autobusa, autobus se i dalje pojavljuje u listi postojećih autobusa za modifikaciju.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Odabrati dugme "Evidencija autobusa"
4. Odabrati tab "Izbriši" i unijeti ispravne registracije nekog autobusa koji postoji u bazi podataka
5. Kliknuti na dugme "Pronađi", a zatim na dugme "Izbriši"
6. Odabrati tab "Modifikuj"

Očekivani rezultat: Autobus koji je upravo izbrisan se ne prikazuje u listi postojećih autobusa

Dobijeni rezultat: Autobus koji je upravo izbrisan se i dalje prikazuje u listi postojećih autobusa i kada se odabere klikom ništa se ne dešava

**Comment by Ilvana** [comment]
Ubaceno osvježavanje kod brisanja autobusa.
