### ISSUE TITLE
Brisanje nepostojećeg korisnika

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#58]
Komponenta:
Obrazac "Korisnički računi"

commit ID:
b0124ce

Opis greške:
Prilikom pokušaja brisanja nepostojećeg korisničkog imena iz sistema javlja se tekst hibernate izuzetka.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Odabrati dugme "Evidencija korisničkih računa"
4. Odabrati tab "Izbriši" i unijeti nepostojeće korisničko ime u polje "Korisničko ime"
5. Kliknuti na dugme "Izbriši korisnika"

Očekivani rezultat: Obavijest da uneseno korisničko ime ne postoji.

Dobijeni rezultat:
http://prntscr.com/7aqe2z

**Comment by Ilvana** [comment]
Popravljeno, dodan if uslov :D
