### ISSUE TITLE
Modifikacija korisnika

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#59]
Komponenta:
Obrazac "Korisnički računi"

commit ID:
b0124ce

Opis greške:
Prilikom unosa nedozvoljene šifre pri modifikaciji korisnika, javlja se tekst hibernate izuzetka.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Odabrati dugme "Evidencija korisničkih računa"
4. Odabrati tab "Modifikuj"
5. Unijeti postojeće korisničko ime i kliknuti na dugme "Pronađi"
6. U polje Šifra unijeti nevalidnu šifru, npr. samo 2 znaka

Očekivani rezultat: Obavijest o nedozvoljenoj šifri

Dobijeni rezultat:
http://prntscr.com/7aqh15 - Pored obavijesti javlja se i tekst izuzetka

**Comment by Ilvana** [comment]
Popravljeno :D
