### ISSUE TITLE
Izuzetak pri pravljenju naloga

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#60]
Komponenta:
Obrazac "Pravljenje naloga"

commit ID:
b0124ce

Opis greške:
Priikom pravljenja naloga javlja se tekst hibernate izuzetka.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer
3. Odabrati dugme "Pravljenje naloga"
4.Odabrati neku autobusku liniju
5. Unijeti datum i vrijeme u polja na obrascu
6. Kliknuti na dugme "Napravi nalog"

Očekivani rezultat: Obavijest o uspješnom ili neuspješnom kreiranju naloga

Dobijeni rezultat:
http://prntscr.com/7aql18

**Comment by Ilvana** [comment]
Unijeto vise linija sa istim brojem linije, koja je jedinstvena za svaku liniju, to je nemoguce izazvati unosom kroz formu.
