### ISSUE TITLE
Izuzetak pri modifikaciji ili brisanju rezervacije

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#61]
Komponenta:
Obrazac "Šalterski radnik"

commit ID:
b0124ce

Opis greške:
Prilikom modifikacije ili brisanja rezervacije javlja se obavijest sa tekstom hibernate izuzetka.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao šalterski radnik
3. Odabrati tab "Modifikacija i brisanje"
4.Odabrati neku rezervaciju
5. Kliknuti na dugme "Modifikuj" ili  na dugme "Obriši"

Očekivani rezultat: Potvrda o uspješnoj ili neuspješnoj modifikaciji rezervacije odnosno brisanja rezervacije

Dobijeni rezultat:
http://prntscr.com/7aqptm

**Comment by Ilvana** [comment]
Rucno u bazu je uneseno vise autobuskih linija sa istim brojem linije, sto nije moguce uradit preko formi, korisniku ce biti dostupne forme, a ne rucno unosenje u bazu .
