### ISSUE TITLE
Prodaja karte

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#62]
Komponenta:
Obrazac "Šalterski radnik"

commit ID:
b0124ce

Opis greške:
Prilikom pokušaja prodaje karte nemoguće je odabrati odredište i vrijeme iz liste.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao šalterski radnik
3. Odabrati tab "Prodaja"

Očekivani rezultat: Mogućnost izbora odredišta i vremena.

Dobijeni rezultat: Prazni listboxovi za odredište i vrijeme.

**Comment by mirhat** [comment]
nemas nijednu autobusku liniju za taj dan kad si probao! moras unijeti nekoliko linija i onda ce ti se pojaviti odredista u combobox-u.

**Comment by oljubuncic1** [comment]
Jesi li siguran jer mi se u tabovima "Rezervacija" i "Modifikacija i brisanje" uredno prikazuju sve linije koje se nalaze u bazi podataka, samo na tabu "Prodaja" stoje prazne.
