### ISSUE TITLE
Mogućnost unošenja nevalidnog vremena naloga

### ISSUE THREAD

**Issue by oljubuncic1** [SoftverInzenjeringETFSA/SI2014Tim3#63]
Komponenta:
Obrazac "Pravljenje naloga"

commit ID:
b0124ce

Opis greške:
Sistem dozvoljava unos nevalidnog vremena tj. vremena koje izlazi iz opsega dozvoljenih vrijednosti 0-24 za sate i 0-59 za minute.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer
3. Odabrati dugme "Pravljenje naloga"
4. Unijeti validne podatke na polja obrasca uključujući i nevalidno vrijeme, npr 30:00

Očekivani rezultat: Obavijest da je vrijeme nevalidno i sprječavanje dodavanja naloga.

Dobijeni rezultat: Obavijest da je nalog uspješno kreiran.

**Comment by sumejabotulja** [comment]
Dodana validacija za sate i minute.
