### ISSUE TITLE
Izuzetak kod unošenja cijene karte

### ISSUE THREAD

**Issue by azramahmutovic** [SoftverInzenjeringETFSA/SI2014Tim3#64]
Komponenta:
AutobuskeLinijeForma

commit ID:
b0124ced40093fa29e4443ce8bb8122361b49486

Opis problema:
Forma ne prihvata vrijednost Double za cijenu karte

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Evidencija autobuskih linija"
4. Na tabu Dodaj unijeti podatke o liniji http://prntscr.com/7avgmk
5. Kliknuti na "Dodaj"

Dobijeni rezultat:
Program baca izuzetak http://prntscr.com/7avh3b

Očekivani rezultat:
Dodavanje autobuske linije

**Comment by mirhat** [comment]
Ispravljeno
Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/4dcdac84e5298fb220883b7851e24c763a5e9418
