### ISSUE TITLE
Izuzetak kod unošenja perona autobuske linije

### ISSUE THREAD

**Issue by azramahmutovic** [SoftverInzenjeringETFSA/SI2014Tim3#65]
Komponenta:
AutobuskeLinijeForma

commit ID:
b0124ce

Opis problema:
Forma baca izuzetak za peron broj 6

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Evidencija autobuskih linija"
4. Na tabu Dodaj unijeti podatke o liniji http://prntscr.com/7avit9
5. Kliknuti na "Dodaj"

Dobijeni rezultat:
Neuspješno dodavanje linije. Program baca izuzetak http://prntscr.com/7avj3w

Očekivani rezultat:
Dodavanje autobuske linije

**Comment by sumejabotulja** [comment]
Izmjenjena poruka, prilikom klika na button "Dodaj", na način da se ispiše da broj perona treba da bude "< 6" a ne "<=6".
