### ISSUE TITLE
Neupješno generisanje izvještaja za linije

### ISSUE THREAD

**Issue by azramahmutovic** [SoftverInzenjeringETFSA/SI2014Tim3#66]
Komponenta:
IzvjestajiForma

commit ID:
b0124ce

Opis problema:
Program ne generiše pravilan izvještaj o autobuskim linijama

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Izvještaji"
4. Na tabu "Autobuske linije" unijeti datume i vrijeme http://prntscr.com/7avp1j
5. Kliknuti na "Generiši izvještaj"

Dobijeni rezultat:
Kreirani izvještaj sadrži 0 linija, iako u bazi postoje autobuske linije u tom periodu http://prntscr.com/7avoca

Očekivani rezultat:
Izvještaj sa svim linijima iz tog perioda

**Comment by Ilvana** [comment]
Popravljeno
