### ISSUE TITLE
Autobus može da se modifikuje samo jednom

### ISSUE THREAD

**Issue by azramahmutovic** [SoftverInzenjeringETFSA/SI2014Tim3#67]
Komponenta:
AutobusiForma

commit ID:
b0124ce

Opis problema:
Nakon modifikacije autobusa, autobus više ne može da se izabere iz liste

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Evidencija autobusa"
4. Na tabu Modifikuj izabrati autobus iz liste i promijeniti kapacitet
5. Kliknuti na "Izmijeni"
6. Izabrati isti autobus iz liste

Dobijeni rezultat:
Autobus više ne može da se izabere iz liste i izmijeni

Očekivani rezultat:
Mogućnost višestruke modifikacije

**Comment by Ilvana** [comment]
Popravljeno, sa dodavanjem osvjezavanja
