### ISSUE TITLE
Linija sa autobusom i vozačem koji su već dodijeljeni drugoj liniji

### ISSUE THREAD

**Issue by azramahmutovic** [SoftverInzenjeringETFSA/SI2014Tim3#68]
Komponenta:
AutobuskeLinijeForma

commit ID:
b0124ce

Opis problema:
Moguće je kreirati liniju sa autobusom i vozačem koji su već dodijeljeni drugoj liniji

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Evidencija autobuskih linija"
4. Na tabu Dodaj unijeti podatke o liniji
5. Kliknuti na "Dodaj"
6. Dodati drugu liniju koja kreće u isto vrijeme sa istim vozačem i autobusom
7. Kliknuti na "Dodaj"

Dobijeni rezultat:
Program dodaje obje linije

Očekivani rezultat:
Izuzetak kod dodavanja druge linije

**Comment by Ilvana** [comment]
Prilikom intervju-a je receno da autobus i vozac mogu biti na vise linija, nije srs-om specificirano
