### ISSUE TITLE
Neuspješna rezervacija karte

### ISSUE THREAD

**Issue by azramahmutovic** [SoftverInzenjeringETFSA/SI2014Tim3#69]
Komponenta:
SalterskiRadnikForma

commit ID:
b0124ce

Opis problema:
Nije moguće rezervisati kartu

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao šalterski radnik
3. Na tabu rezervacija izabrati postojeću liniju, vrijeme polaska i unijeti ime i prezime http://prntscr.com/7awt2x
5. Kliknuti na "Rezerviši"

Dobijeni rezultat:
Program izbacuje poruku http://prntscr.com/7awtg8

Očekivani rezultat:
Uspješna rezervacija

**Comment by mirhat** [comment]
Ispravljeno
Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/dc9039ed5b684b91379b3aa8b9e5245fbefe2de8
