### ISSUE TITLE
Neuspješna kupovina karte

### ISSUE THREAD

**Issue by azramahmutovic** [SoftverInzenjeringETFSA/SI2014Tim3#70]
Komponenta:
SalterskiRadnikForma

commit ID:
b0124ce

Opis problema:
Nije moguće izabrati odredište i vrijeme pri kupovini karte

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao šalterski radnik
3. Na tabu prodaja izabrati ComboBox Odrediste http://prntscr.com/7awz8w

Dobijeni rezultat:
Nije moguće odabrati nijedno odredište iako u bazi postoje autobuske linije

Očekivani rezultat:
Uspješna kupovina karte

**Comment by mirhat** [comment]
moras imati autobusku liniju za taj dan kad hoces da prodas kartu. Objasnjavao sam orhanu vec to

**Comment by azramahmutovic** [comment]
mislis kao danasnji dan?

**Comment by mirhat** [comment]
da da
