### ISSUE TITLE
Nemogućnost dodavanja novog korisničkog računa

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#71]
Komponenta:
Korisnički računi

commitID: e0b9b7b968
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/KorisniciForma.java

Opis problema:
Nemogućnost kreiranja korisničkog računa, javlja se greška da treba unijeti password koji sadrzi minimalno 8 znakova, ali greška se javlja i kad je taj zahtjev ispunjen

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Korisnički računi" 
4. Kliknuti na "dodaj"
5. Unijeti korisničko ime i šifru 
6. Kliknuti na dodaj korisnika

Dobijeni rezultat:
http://prntscr.com/7b53sk

Očekivani rezultat:
Dodan novi korisnički rezultat i poruka o tom.

**Comment by Ilvana** [comment]
Password po srs-u mora imati jedno slovo i broj i imati duzinu 8 karaktera
