### ISSUE TITLE
Nemogućnost modifikovanja korisničkog računa

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#72]
Komponenta:
Korisnički računi

commitID: e0b9b7b968
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/KorisniciForma.java

Opis problema:
Nije moguće modifikovati postojeći korisnički račun.Javlja grešku da nije unesena dovoljno duga šifra, što nije tačno!

Dobiveni rezultat:
http://prntscr.com/7b5qyw

Stanje u bazi : http://prntscr.com/7b5rxv

Očekivani rezultat: uspješno modifikovan korisnički račun u bazi i odgovarajuća poruka o tome.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Korisnički računi" 
4. Kliknuti na "modifikuj"
5. Unijeti korisničko ime i pritisnuti "Pronađi"
6. Napraviti neku promjenu u kroisničkom imenu
7.Kliknuti na "Modifikuj korisnika"

Dobijeni rezultat:
http://prntscr.com/7b53sk

Očekivani rezultat:
Dodan novi korisnički rezultat i poruka o tom.

**Comment by DAhmic** [comment]
podaci su ručno uneseni u bazu, a prema SRS-u šifra "password" nije validna
