### ISSUE TITLE
korisničkog računa-nevalidan podatak u bazi

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#73]
Komponenta:
Korisnički računi

commitID: e0b9b7b968
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/KorisniciForma.java

Opis problema:
U bazi se nalazi podatak koji nije dozvoljen, šifra mora sadržavati bar 8 znakova, kod vas korisnički račun neko ima šifru od 4 znaka.
Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Korisnički računi" 
4. Kliknuti na "modifikuj"
5. Unijeti korisničko ime i pritisnuti "Pronađi" //vec ovdje se vidi šifra od 4 simbola
(6. Napraviti neku promjenu u kroisničkom imenu
7.Kliknuti na "Modifikuj korisnika")

Dobiveni rezultat:
http://prntscr.com/7b5tnb

Očekivani rezultat: Podaci u bazi su u skladu sa ograničenjima.

**Comment by DAhmic** [comment]
korisnik ručno dodan u bazu, preko forme šifra od 4 znaka ne prolazi

**Comment by mirhat** [comment]
Ispravljeno
Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/fa5a7f66290af43f35d44c09c3be6a7f94a4159b
