### ISSUE TITLE
Evidencija autobusa- nejasna poruka o grešci

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#74]
Komponenta:
Evidencija autoba

commitID: e0b9b7b968
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/AutobusiForma.java

Opis problema:
Unijela nevalidne podatke, nedefinisana poruka o grešci, iskače prazan messagebox.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Evidencija autobusa" 
4. Izabrati autobus iz ponuđene liste
5. Unijeti prazan kapacitet i nevalidne tablice
6. Kliknuti na Izmijeni

Dobiveni rezultat:
http://prntscr.com/7b5w6m

Očekivani rezultat:Odgovarajuća poruka o grešci.

**Comment by Ilvana** [comment]
Rijeseno
