### ISSUE TITLE
Evidencija autobusa-ne prolaze validni podaci ako je unesen prvo razmak

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#75]
Komponenta:
Evidencija autoba

commitID: e0b9b7b968
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/AutobusiForma.java

Opis problema:
Ako korisnik slucajno unese space pa potom validne podatke dobiva poruku da je nevalidan format u pitanju, što ne upućuju u čemu je problem.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Evidencija autobusa" 
4. Izabrati autobus iz ponuđene liste
5. Unijeti prazan kapacitet i nevalidne tablice
6. Kliknuti na Izmijeni

Dobiveni rezultat:
http://prntscr.com/7b6442

Očekivani rezultat:Razmaci na početku ne utiču na validnost podataka ili da se dobije odgovarajuća poruka koja upućuje na grešku!

**Comment by mirhat** [comment]
Ispravljeno 
Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/92001ae03712ceab40ac2b55c921080f14aa61a6
