### ISSUE TITLE
"false" poruka kod Izvještaji- vozač

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#76]
Komponenta:
Izvještaji

commitID:e0b9b7b968
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/IzvjestajiForma.java

Opis problema:
Kada želimo napraviti izvještaj za vozača, pojavi se poruka false iako su podaci validni.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Izvještaji" 
4. Zatim odabrati tab "Vozači"
5. Unesemo jmbg postojećeg vozača
6. Kliknuti na "Generiši izvještaj"

Dobiveni rezultat:
http://prntscr.com/7b6hps

Stanje u bazi: http://prntscr.com/7b6ily

Očekivani rezultat:Generisan izvještaj bez suvišnih/neodgovarajućih poruka.

**Comment by Ilvana** [comment]
Izbrisan viska messege box :D
