### ISSUE TITLE
Evidencija autobusa-dodavanje

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#77]
Komponenta:
Evidencija autobusa

commitID:e0b9b7b968
https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/AutobusiForma.java

Opis problema:
Kada želim dodati autobus, prijavljuje mi poruku kao da je nevalidan format tablice iako sam unijela onako kako je napisano.Možda je nedovoljno jasno definisan format koji se zahtijeva ili iz nekog razlogs ne prihvata sve tablice koje bi trebalo da odgovaraju šablonu.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Evidencija autobusa" 
4. Izabrati tab "Dodaj"
5. Popuniti polja validnim podacima (unijeti tablice R23-K-321)
6. Kliknuti na Dodaj

Dobiveni rezultat:
http://prntscr.com/7b6ndv

Očekivani rezultat:Dodan model u bazu i ispisana odgovarajuća poruka o tom!

**Comment by DAhmic** [comment]
Prema SRS-u (3.2.9. Evidencija autobusa), ovo nisu validne tablice.
![image](https://cloud.githubusercontent.com/assets/10135153/7899482/9b306d28-0724-11e5-8c66-f7e72ad93bcf.png)
