### ISSUE TITLE
Izvještaji

### ISSUE THREAD

**Issue by Zannaa** [SoftverInzenjeringETFSA/SI2014Tim3#78]
Komponenta:
Izvještaji

commitID: e0b9b7b968

https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/blob/master/projekt/src/main/java/ba/unsa/etf/si/projekt/forme/IzvjestajiForma.java

Opis problema:
Kada želimo napraviti izvještaj, a pritom nam je neki prijašnji izvještaj minimiziran ili otvoren, dobivamo poruku da je neuspješno kreiranje izvještaja.Pri tome ništa ne upućuje na to da je problem u otvorenom izvještaju, nego korisnik pomisli da je greška u podacima.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao administrator
3. Kliknuti na dugme "Izvještaji" 
4. Zatim odabrati tab "Vozači"
5. Unesemo  validne podatke
6. Kliknuti na "Generiši izvještaj"

Dobiveni rezultat:
http://prntscr.com/7b76zj

Stanje u bazi: http://prntscr.com/7b77o8

Očekivani rezultat:Učitavanje novog izvještaja u pdf reader ili izvještavanje o tome da je potrebno zatvoriti prethodni izvještaj.

**Comment by mirhat** [comment]
Ispravljeno. Prikazuje se poruka kada je vec otvoren izvjestaj.
Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim3/commit/ae69d333d701df8acc1cedba4e501b8fc98753d3
